config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post "/generate_api_keys", to: "api_keys#create"
  
  # /api endpoints
  namespace :api do
    namespace :v1 do
      # /api/v1/chat_messages
      resources :chat_messages, only: [:create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :user
  has_many :api_requests
end

app/models/api_request.rb
class ApiRequest < ApplicationRecord
  belongs_to :api_key, optional: true
  belongs_to :user, optional: true
  serialize :request_details, coder: JSON, type: Object
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_messages_api_request.rb
class ChatMessagesApiRequest < ApiRequest
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :api_keys, dependent: :destroy
  has_many :api_requests
  has_many :chat_messages_api_requests
end

app/controllers/api/v1/chat_messages_controller.rb
class Api::V1::ChatMessagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authorize_request
  def create
    if params[:prompt].nil? || params[:prompt].empty?
      return render json: { message: "You must pass a prompt value with content" }, status: 400
    end

    client = Ollama.new(
      credentials: { address: 'http://localhost:11434' },
      options: { server_sent_events: true }
    )

    result = client.generate(
      { model: 'llama3.1',
        prompt:  params[:prompt] }
    )

    ai_response = result.map { |r| r['response'] }.join
    request_details = request.params.except(:controller, :action)
    request_details["original_url"] = request.original_url
    ChatMessagesApiRequest.create(api_key: @api_key, ai_response: ai_response, user: @api_key.user, request_details: request_details)
    render json: { results: ai_response }, status: 200
  end

  private

  def authorize_request
    @api_key = ApiKey.where(token: params[:token]).first
    if !@api_key
      render json: { message: "You must pass a token paremeter with a valid api key. If you need to generate an api key visit our website http://localhost:3000" }, status: 400
    end
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  def create
    @api_key = current_user.api_keys.create(token: SecureRandom.hex(16))
    render turbo_stream: turbo_stream.append("api-keys", partial: "dashboard/api_key", locals: { api_key: @api_key })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_api_key.html.erb
<div class="flex gap-2 items-center p-2 text-xl rounded-lg bg-gray-500" data-controller="clipboard">
  <%= text_field_tag :blababa, :api_key, value: api_key.token, class: "hidden", data: { clipboard_target: "input" } %>
  <div>
    <%= api_key.token[0...3] %>
    <%= api_key.token.chars.map { |chr| "*" }.join("") %>
  </div>
  <div>
    <%= link_to "#", data: { action: "clipboard#copy", clipboard_target: "copyButton" } do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
      </svg>
    <% end %>

    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 fill-green-500 text-white hidden" data-clipboard-target="success">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
    </svg>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="w-full min-h-screen flex flex-col items-center pt-24 bg-gradient-to-br from-gray-900 to-indigo-900">
  <h1 class="font-bold text-7xl text-white text-center">Your Dashboard</h1>
  <p class="text-lg text-gray-200 max-w-md text-center">This is the place where you can manage all of your account settings </p>
  <div class="max-w-7xl w-full p-4 rounded-lg bg-gray-700 min-h-[60vh] mt-8"> 
    <div class="flex flex-col md:flex-row gap-8 md:gap-0 justify-between">
      <div class="max-w-lg w-full mx-auto flex flex-col items-center"> 
        <h2 class="text-3xl text-gray-200"> Endpoint URL </h2>
        <div class="p-2 rounded-lg bg-gray-500 text-gray-200"> 
          <%= api_v1_chat_messages_url %>
        </div>
      </div>

      <div class="max-w-lg w-full mx-auto flex flex-col items-center"> 
        <h2 class="text-3xl text-gray-200"> Example Request </h2>
        <div class="p-2 rounded-lg bg-gray-500 text-gray-200"> 
          curl --location <%= api_v1_chat_messages_url %> \
              --form 'token="<%= current_user&.api_keys&.last&.token || "14c39132116a6ac66d8b403c39646a8b" %>"' \
              --form 'prompt="Whats going on?"'
        </div>
      </div>
    </div>

    <div class="grid md:grid-cols-2 mt-4">
      <div class="w-full flex flex-col gap-4 mt-8 md:mt-0">
        <div class="flex items-center justify-between w-full md:w-3/4">
          <h2 class="text-4xl text-gray-200"> Your API Keys </h2>
          <%= link_to "Generate New API Key", generate_api_keys_path, class: "bg-green-500 p-2 rounded-lg text-green-100",
              data: { turbo_method: :post } %>
        </div>
        <div id="api-keys" class="flex flex-col max-w-xl gap-4">
          <%= render partial: "api_key", collection: current_user.api_keys %>
        </div>
      </div>

      <div class="w-full flex flex-col gap-4 mt-8 md:mt-0"> 
        <h3 class="text-4xl text-gray-200"> API Usage </h3>
        <div class="bg-gray-500 rounded-lg text-gray-100 p-4"> 
          Api Requests Count: <%= current_user.api_requests.count %>
        </div>

        <div class="bg-gray-500 rounded-lg text-gray-100 p-4"> 
          AI Generations Count: <%= current_user.api_requests.where.not(ai_response: nil).count %>
        </div>

        <div class="bg-gray-500 rounded-lg text-gray-100 p-4"> 
          Requests this month: <%= current_user.api_requests.where(created_at: Time.now.beginning_of_month..).count %>
        </div>

        <div class="bg-gray-500 rounded-lg text-gray-100 p-4"> 
          Usage Cost: <%= number_to_currency(current_user.api_requests.where(created_at: Time.now.beginning_of_month..).count * API_REQUEST_PRICE) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AiApiSaas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>